_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True  True  True  True]'
_last_obs:
    value: |-
        [[-5.76516725e-02  8.28080773e-02 -7.49374777e-02 -3.74397859e-02
          -7.23716095e-02 -8.43368098e-02  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           8.22300255e-01  1.44093230e-01 -4.38659973e-02  5.01999974e-01
          -5.00000007e-02 -1.17500000e-01 -3.20300251e-01 -1.94093227e-01
          -7.36339986e-02  3.81688863e-01  1.83604043e-02  2.63719987e-02
           2.38654390e-02  1.19234985e-02  2.30482835e-02  2.68588569e-02
           0.00000000e+00  0.00000000e+00  0.00000000e+00]
         [-9.02116820e-02 -2.77639888e-02 -3.89700308e-02  2.68132091e-02
           9.59006026e-02  9.58276168e-02  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           8.41712058e-01  1.15713052e-01  3.28540988e-02  5.01999974e-01
          -5.00000007e-02 -1.17500000e-01 -3.39712024e-01 -1.65713057e-01
          -1.50354102e-01  4.06781793e-01  2.87298355e-02  8.84203520e-03
           1.24108372e-02  8.53923801e-03  3.05415932e-02  3.05183493e-02
           0.00000000e+00  0.00000000e+00  0.00000000e+00]
         [-9.27963406e-02  3.45246606e-02 -1.50038702e-02  1.12601193e-02
           9.64635164e-02 -2.34922464e-03  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           8.36100519e-01  1.14082463e-01 -2.80167256e-02  5.01999974e-01
          -5.00000007e-02 -1.17500000e-01 -3.34100485e-01 -1.64082468e-01
          -8.94832760e-02  3.82823020e-01  2.95529738e-02  1.09951152e-02
           4.77830227e-03  3.58602521e-03  3.07208654e-02  7.48160703e-04
           0.00000000e+00  0.00000000e+00  0.00000000e+00]
         [ 4.04675230e-02  8.07316154e-02 -5.21665961e-02 -7.28149489e-02
          -1.84428245e-02  7.37773553e-02  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           8.09961557e-01  2.24387899e-01 -5.09422719e-02  5.01999974e-01
          -5.00000007e-02 -1.17500000e-01 -3.07961524e-01 -2.74387896e-01
          -6.65577278e-02  4.17802542e-01  1.28877470e-02  2.57107057e-02
           1.66135654e-02  2.31894739e-02  5.87351108e-03  2.34959722e-02
           0.00000000e+00  0.00000000e+00  0.00000000e+00]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x13a0ec7d0>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 100000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.21.3
        e:
            8uxnlao6gu9vhai6w6bv398zaw7cyuzc:
                apple:
                    ecpuCores: 4
                    gpuCores: 20
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 10
                    ramTotalBytes: "25769803776"
                codePath: PPO.py
                codePathLocal: PPO.py
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "994662584320"
                        used: "248209891328"
                email: js6897@columbia.edu
                executable: /Users/jaiselsingh/Desktop/research/.venv/bin/python
                git:
                    commit: 23beebb5c13ab4c89a9ffc08f1739c4fd0f9de6d
                    remote: git@github.com:jaiselsingh1/ur5_research.git
                host: MacBook-Pro-27.local
                memory:
                    total: "25769803776"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/jaiselsingh/Desktop/research/PPO.py
                python: CPython 3.12.5
                root: /Users/jaiselsingh/Desktop/research
                startedAt: "2025-09-03T14:34:20.601134Z"
                writerId: 8uxnlao6gu9vhai6w6bv398zaw7cyuzc
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 2
                - 16
                - 22
                - 35
            "4": 3.12.5
            "5": 0.21.3
            "12": 0.21.3
            "13": darwin-arm64
action_noise:
    value: None
action_space:
    value: Box(-1.0, 1.0, (6,), float64)
algo:
    value: PPO
algorithm:
    value: PPO
batch_size:
    value: 64
clip_range:
    value: FloatSchedule(ConstantSchedule(val=0.2))
clip_range_vf:
    value: None
device:
    value: cpu
ent_coef:
    value: 0
env:
    value: <stable_baselines3.common.vec_env.subproc_vec_env.SubprocVecEnv object at 0x123a42e10>
env_id:
    value: UR5-v0
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
log_std_init:
    value: -1.38
lr_schedule:
    value: FloatSchedule(ConstantSchedule(val=0.0003))
max_grad_norm:
    value: 0.5
n_envs:
    value: 4
n_epochs:
    value: 10
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
num_cpu:
    value: 4
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (31,), float32)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=31, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=31, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=6, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{''log_std_init'': -1.6}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x123af3f80>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1756910063410376000
target_kl:
    value: None
tensorboard_log:
    value: tensorboard_log
total_timesteps:
    value: 100000
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
