_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True  True  True  True]'
_last_obs:
    value: |-
        [[ 8.35962445e-02 -2.21714086e-04 -3.88841555e-02  8.36107600e-03
          -5.13835438e-02 -7.65615180e-02  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           7.96809554e-01  2.58777797e-01  9.85338911e-03  5.01999974e-01
          -5.00000007e-02 -1.17500000e-01 -2.94809520e-01 -3.08777779e-01
          -1.27353385e-01  4.45505619e-01  2.66230069e-02  7.06095816e-05
           1.23834889e-02  2.66276323e-03  1.63641851e-02  2.43826509e-02
           0.00000000e+00  0.00000000e+00  0.00000000e+00]
         [ 2.76575126e-02  1.42087676e-02 -4.92195077e-02  5.69325015e-02
          -9.21702757e-02 -1.87046006e-02  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           8.01725507e-01  2.13353172e-01  2.38941796e-03  5.01999974e-01
          -5.00000007e-02 -1.17500000e-01 -2.99725473e-01 -2.63353169e-01
          -1.19889416e-01  4.16609794e-01  8.80812481e-03  4.52508545e-03
           1.56750027e-02  1.81313697e-02  2.93535907e-02  5.95687935e-03
           0.00000000e+00  0.00000000e+00  0.00000000e+00]
         [-8.57113376e-02 -6.23015240e-02  2.50297580e-02  9.41620022e-02
          -7.46651217e-02  2.30655652e-02  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           8.18057895e-01  1.21636212e-01  3.60886864e-02  5.01999974e-01
          -5.00000007e-02 -1.17500000e-01 -3.16057891e-01 -1.71636209e-01
          -1.53588682e-01  3.91076803e-01  2.72966027e-02  1.98412500e-02
           7.97126070e-03  2.99878977e-02  2.37787012e-02  7.34572159e-03
           0.00000000e+00  0.00000000e+00  0.00000000e+00]
         [ 7.96332881e-02 -8.33881460e-03  7.14824945e-02 -3.51852947e-03
           6.41173869e-02  5.19048683e-02  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           7.98274755e-01  2.55592972e-01 -2.68447306e-02  5.01999974e-01
          -5.00000007e-02 -1.17500000e-01 -2.96274781e-01 -3.05592954e-01
          -9.06552672e-02  4.35182929e-01  2.53609195e-02  2.65567331e-03
           2.27651261e-02  1.12055079e-03  2.04195511e-02  1.65302120e-02
           0.00000000e+00  0.00000000e+00  0.00000000e+00]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x12a8db530>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 100000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.21.3
        e:
            bdqf1tk0x5b7zl610np62yzqze9zrlt0:
                apple:
                    ecpuCores: 4
                    gpuCores: 20
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 10
                    ramTotalBytes: "25769803776"
                codePath: PPO.py
                codePathLocal: PPO.py
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "994662584320"
                        used: "248143822848"
                email: js6897@columbia.edu
                executable: /Users/jaiselsingh/Desktop/research/.venv/bin/python
                git:
                    commit: 788c0092f2f2da533a705f114d99fe54ba848a2f
                    remote: git@github.com:jaiselsingh1/ur5_research.git
                host: MacBook-Pro-27.local
                memory:
                    total: "25769803776"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/jaiselsingh/Desktop/research/PPO.py
                python: CPython 3.12.5
                root: /Users/jaiselsingh/Desktop/research
                startedAt: "2025-09-03T15:02:14.267627Z"
                writerId: bdqf1tk0x5b7zl610np62yzqze9zrlt0
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 2
                - 16
                - 22
                - 35
            "4": 3.12.5
            "5": 0.21.3
            "12": 0.21.3
            "13": darwin-arm64
action_noise:
    value: None
action_space:
    value: Box(-1.0, 1.0, (6,), float64)
algo:
    value: PPO
algorithm:
    value: PPO
batch_size:
    value: 64
clip_range:
    value: FloatSchedule(ConstantSchedule(val=0.2))
clip_range_vf:
    value: None
device:
    value: cpu
ent_coef:
    value: 0
env:
    value: <stable_baselines3.common.vec_env.subproc_vec_env.SubprocVecEnv object at 0x11c7624b0>
env_id:
    value: UR5-v0
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0002
log_std_init:
    value: -1.38
lr_schedule:
    value: FloatSchedule(ConstantSchedule(val=0.0002))
max_grad_norm:
    value: 0.5
n_envs:
    value: 4
n_epochs:
    value: 10
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
num_cpu:
    value: 4
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (31,), float32)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=31, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=31, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=6, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{''log_std_init'': -1.6}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x11c4be360>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1756911736757890000
target_kl:
    value: None
tensorboard_log:
    value: tensorboard_log
total_timesteps:
    value: 100000
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
