_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True  True  True  True]'
_last_obs:
    value: |-
        [[ 1.8901428e-02  7.4314508e-03  1.8286360e-02  1.9028233e-03
           1.8093538e-02  3.8793936e-02  0.0000000e+00  0.0000000e+00
           0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
           8.1221908e-01  2.0682466e-01 -1.8741058e-02  5.0199997e-01
          -5.0000001e-02 -1.1750000e-01 -3.1021908e-01 -2.5682467e-01
          -9.8758943e-02  4.1466627e-01  6.0195634e-03  2.3667042e-03
           5.8236816e-03  6.0599472e-04  5.7622734e-03  1.2354757e-02
           0.0000000e+00  0.0000000e+00  0.0000000e+00]
         [-6.1956953e-02 -4.1839186e-02 -9.9246092e-02 -6.1006062e-02
          -9.0199009e-02  5.1786434e-02  0.0000000e+00  0.0000000e+00
           0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
           8.3496720e-01  1.3968451e-01  6.7880996e-02  5.0199997e-01
          -5.0000001e-02 -1.1750000e-01 -3.3296719e-01 -1.8968453e-01
          -1.8538100e-01  4.2569175e-01  1.9731514e-02  1.3324581e-02
           3.1607036e-02  1.9428682e-02  2.8725799e-02  1.6492495e-02
           0.0000000e+00  0.0000000e+00  0.0000000e+00]
         [ 4.3769985e-02 -3.5864964e-02  9.7250581e-02  4.5487560e-02
           2.5202505e-02  9.8812185e-02  0.0000000e+00  0.0000000e+00
           0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
           7.9905367e-01  2.2660430e-01 -1.3996250e-02  5.0199997e-01
          -5.0000001e-02 -1.1750000e-01 -2.9705369e-01 -2.7660429e-01
          -1.0350375e-01  4.1888407e-01  1.3939486e-02  1.1421963e-02
           3.0971523e-02  1.4486484e-02  8.0262758e-03  3.1468850e-02
           0.0000000e+00  0.0000000e+00  0.0000000e+00]
         [-3.5791264e-03 -7.6041743e-02  3.5815429e-02 -4.9479600e-02
           2.3678096e-02 -7.8493327e-02  0.0000000e+00  0.0000000e+00
           0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
           8.2680434e-01  1.8846890e-01  4.3125261e-02  5.0199997e-01
          -5.0000001e-02 -1.1750000e-01 -3.2480434e-01 -2.3846890e-01
          -1.6062526e-01  4.3378076e-01  1.1398492e-03  2.4217116e-02
           1.1406187e-02  1.5757835e-02  7.5407946e-03  2.4997873e-02
           0.0000000e+00  0.0000000e+00  0.0000000e+00]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x1495bc110>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 100000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.21.3
        e:
            l8kcm3p35nx31bbcq1wfuih7afemuq7x:
                apple:
                    ecpuCores: 4
                    gpuCores: 20
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 10
                    ramTotalBytes: "25769803776"
                codePath: PPO.py
                codePathLocal: PPO.py
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "994662584320"
                        used: "248185241600"
                email: js6897@columbia.edu
                executable: /Users/jaiselsingh/Desktop/research/.venv/bin/python
                git:
                    commit: 788c0092f2f2da533a705f114d99fe54ba848a2f
                    remote: git@github.com:jaiselsingh1/ur5_research.git
                host: MacBook-Pro-27.local
                memory:
                    total: "25769803776"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/jaiselsingh/Desktop/research/PPO.py
                python: CPython 3.12.5
                root: /Users/jaiselsingh/Desktop/research
                startedAt: "2025-09-03T15:13:38.571082Z"
                writerId: l8kcm3p35nx31bbcq1wfuih7afemuq7x
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 2
                - 16
                - 22
                - 35
            "4": 3.12.5
            "5": 0.21.3
            "12": 0.21.3
            "13": darwin-arm64
action_noise:
    value: None
action_space:
    value: Box(-1.0, 1.0, (6,), float64)
algo:
    value: PPO
algorithm:
    value: PPO
batch_size:
    value: 64
clip_range:
    value: FloatSchedule(ConstantSchedule(val=0.2))
clip_range_vf:
    value: None
device:
    value: cpu
ent_coef:
    value: 0
env:
    value: <stable_baselines3.common.vec_env.subproc_vec_env.SubprocVecEnv object at 0x11ae11b80>
env_id:
    value: UR5-v0
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0002
log_std_init:
    value: -1.38
lr_schedule:
    value: FloatSchedule(ConstantSchedule(val=0.0002))
max_grad_norm:
    value: 0.5
n_envs:
    value: 4
n_epochs:
    value: 10
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
num_cpu:
    value: 4
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (31,), float32)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=31, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=31, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=6, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{''log_std_init'': -1.6}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x11aa52a20>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1756912421093477000
target_kl:
    value: None
tensorboard_log:
    value: tensorboard_log
total_timesteps:
    value: 100000
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
